# port for serving the app
server:
  port: 1010

# app name
spring:
  application:
    name: springSecurity

# spring security login config
  security:
    user:
      name: khay
      password: password

# database credentials
  datasource:
    url: jdbc:postgresql://localhost:5432/springsecurity
    username: playground
    password: password

# jpa & hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true